project:
  type: book
  output-dir: docs

book:
  title: "Social Network Analysis in R"
  author: "Adam Urban"
  date: "22/10/2024"
  page-navigation: true
  search: true
  repo-url: https://github.com/urbana98/Quarto-book
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

